In [2]:
import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_train.csv")
#display the first 5 rows of the table to verify
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [16]:
import pandas as pd
df_brca=pd.read_csv("/content/brca.csv.zip", encoding='latin1', on_bad_lines='skip', engine='python')
print(f"total rows:{df_brca.shape[0]}, total column:{df_brca.shape[1]}")
df_brca.head()

total rows:705, total column:1937

,rs_CLEC3A,rs_CPB1,rs_SCGB2A2,rs_SCGB1D2,rs_TFF1,rs_MUCL1,rs_GSTM1,rs_PIP,rs_ADIPOQ,rs_ADH1B,...,pp_p27.pT198,pp_p38.MAPK,pp_p38.pT180.Y182,pp_p53,pp_p62.LCK.ligand,pp_p70S6K,pp_p70S6K.pT389,pp_p90RSK,pp_p90RSK.pT359.S363,vital.status
0,0.892818,6.580103,14.123672,10.606501,13.189237,6.649466,10.520335,10.338490,10.248379,10.229970,...,-0.043330,-0.002598,0.449228,-0.375230,-0.691766,-0.337863,-0.178503,0.011638,-0.207257,0
1,0.000000,3.691311,17.116090,15.517231,9.867616,9.691667,8.179522,7.911723,1.289598,1.818891,...,-0.220764,0.220809,1.035115,-0.074136,0.279067,0.292925,-0.155242,-0.089365,0.267530,0
2,3.748150,4.375255,9.658123,5.326983,12.109539,11.644307,10.517330,5.114925,11.975349,11.911437,...,0.010615,-0.133214,0.344969,-0.351936,0.219910,0.308110,-0.190794,-0.222150,-0.198518,0
3,0.000000,18.235519,18.535480,14.533584,14.078992,8.913760,10.557465,13.304434,8.205059,9.211476,...,0.064070,-0.384008,0.678042,0.096329,-0.266554,-0.079871,-0.463237,0.522998,-0.046902,0
4,0.000000,4.583724,15.711865,12.804521,8.881669,8.430028,12.964607,6.806517,4.294341,5.385714,...,-0.065488,0.209858,0.920408,0.042210,-0.441542,-0.152317,0.511386,-0.096482,0.037473,0

In [18]:
import numpy as np
avg=np.mean(df_brca['rs_CLEC3A'])
print(f'Average: {avg}')

Average: 4.5471968163390155

In [20]:
import numpy as np
all_mean = df_brca.mean(numeric_only=True)
print(all_mean.head())

rs_CLEC3A     4.547197
rs_CPB1       6.487979
rs_SCGB2A2    9.516678
rs_SCGB1D2    7.351940
rs_TFF1       8.179439
dtype: float64

In [23]:
import numpy as np
sample_array=df_brca['rs_CLEC3A']
reshaped_data = sample_array.to_numpy().reshape(-1,1)
print("reshaped data:", reshaped_data)

reshaped data: [[ 0.89281843]
 [ 0.        ]
 [ 3.7481499 ]
 [ 0.        ]
 [ 0.        ]
 [ 0.60283691]
 [ 5.65431237]
 [ 2.37094541]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [12.08081283]
 [ 0.54744983]
 [10.22000219]
 [ 0.        ]
 [ 1.22502808]
 [ 0.        ]
 [ 5.2076274 ]
 [ 0.        ]
 [ 4.3764571 ]
 [ 5.27236291]
 [12.67569735]
 [ 0.        ]
 [ 0.        ]
 [ 1.68602982]
 [ 4.72636804]
 [ 5.39238612]
 [ 3.76062548]
 [11.20323334]
 [ 7.25464884]
 [ 0.        ]
 [ 3.30977282]
 [ 5.7718803 ]
 [11.71497604]
 [10.41783722]
 [ 0.        ]
 [ 0.        ]
 [ 5.17298748]
 [ 0.        ]
 [13.50333239]
 [ 7.5638735 ]
 [ 1.69950721]
 [ 0.        ]
 [ 1.52240734]
 [ 2.19115202]
 [ 4.05538657]
 [10.83083223]
 [ 2.32538641]
 [ 0.38106183]
 [10.2537331 ]
 [15.89298525]
 [ 0.97548345]
 [ 0.3971458 ]
 [ 0.33993549]
 [12.95598998]
 [ 4.87683124]
 [15.35162847]
 [ 0.        ]
 [12.12825144]
 [ 0.        ]
 [ 0.        ]
 [ 9.94815096]
 [ 6.96074221]
 [ 2.18922364]
 [11.33048742]
 [13.32305482]
 [ 0.        ]
 [ 0.        ]
 [ 9.87389239]
 [ 2.42080575]
 [ 1.70686204]
 [ 0.        ]
 [ 5.20752589]
 [ 0.        ]
 [ 2.66582479]
 [ 0.        ]
 [ 3.35491756]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 1.61183337]
 [ 6.75712328]
 [11.52212668]
 [10.06458367]
 [13.70909585]
 [11.21623676]
 [ 2.16684396]
 [ 0.        ]
 [ 7.07169189]
 [13.14997008]
 [ 0.        ]
 [ 2.87947053]
 [ 0.59979385]
 [ 0.        ]
 [ 1.30082659]
 [ 0.        ]
 [ 1.04397437]
 [ 1.0316775 ]
 [ 0.        ]
 [13.48418474]
 [ 1.23486915]
 [12.12443389]
 [ 1.28404026]
 [ 6.17317941]
 [ 0.        ]
 [ 2.17613125]
 [13.83037825]
 [ 0.        ]
 [ 7.32450641]
 [ 2.2061118 ]
 [15.03060106]
 [ 1.57874554]
 [10.9672517 ]
 [16.52837306]
 [ 0.        ]
 [ 7.34680003]
 [10.63033493]
 [ 1.95058039]
 [ 5.34898304]
 [ 2.03097164]
 [10.74333462]
 [ 9.22922908]
 [ 0.        ]
 [ 0.39813143]
 [ 0.        ]
 [12.12645317]
 [ 3.9068906 ]
 [ 0.        ]
 [14.74406618]
 [ 0.97614364]
 [ 8.08724377]
 [ 5.44936328]
 [ 0.        ]
 [ 2.04208396]
 [ 8.83947403]
 [ 2.16665118]
 [ 3.45902498]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.57492498]
 [10.75648911]
 [13.12604169]
 [12.24561319]
 [ 0.        ]
 [13.61415694]
 [ 7.91199171]
 [13.69939628]
 [12.05827949]
 [14.31966763]
 [ 0.        ]
 [10.45792502]
 [12.10667937]
 [ 0.        ]
 [ 0.        ]
 [ 2.30035805]
 [ 0.5212518 ]
 [ 6.61436827]
 [15.42528814]
 [11.08534823]
 [ 8.0446045 ]
 [ 1.18852753]
 [ 2.36179643]
 [ 7.47899445]
 [13.15881032]
 [ 1.56369507]
 [ 0.        ]
 [ 6.35315388]
 [ 8.63020996]
 [14.65296806]
 [ 0.466862  ]
 [ 0.        ]
 [12.30776758]
 [10.38796905]
 [ 3.96813684]
 [10.49307066]
 [ 5.00560659]
 [ 2.77230797]
 [ 3.28445491]
 [ 0.        ]
 [ 0.        ]
 [14.63497418]
 [ 1.10547694]
 [ 6.37925705]
 [ 0.8793921 ]
 [ 0.        ]
 [10.95186321]
 [ 0.        ]
 [ 9.60567063]
 [ 0.        ]
 [ 7.99167943]
 [ 8.40942488]
 [ 0.        ]
 [15.95738587]
 [ 5.37623133]
 [ 1.47129153]
 [15.50436042]
 [ 4.22240273]
 [ 8.02002264]
 [ 3.05944181]
 [10.93977041]
 [ 0.        ]
 [ 3.51863585]
 [12.09040659]
 [16.07601612]
 [ 4.11658101]
 [ 0.        ]
 [ 0.        ]
 [ 9.00817031]
 [ 2.79761484]
 [ 6.81659843]
 [10.93142297]
 [10.58284866]
 [ 0.        ]
 [ 2.04764308]
 [ 0.32803219]
 [14.86058297]
 [ 0.85917446]
 [ 1.90149446]
 [ 0.        ]
 [ 0.80941444]
 [10.89700016]
 [15.11558766]
 [ 3.16212945]
 [ 4.42798825]
 [ 5.971401  ]
 [ 5.61265622]
 [ 0.47995483]
 [ 0.        ]
 [ 2.16185544]
 [ 4.90690502]
 [ 5.40742074]
 [ 4.15549829]
 [ 1.06550338]
 [ 0.        ]
 [ 0.        ]
 [ 1.86892377]
 [ 1.22515151]
 [ 2.31208426]
 [ 0.37928825]
 [13.94934109]
 [12.21085048]
 [ 0.        ]
 [ 2.14336076]
 [ 5.18968226]
 [ 2.56354865]
 [ 1.23486915]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.65122394]
 [ 0.74053905]
 [ 0.        ]
 [ 6.35860197]
 [ 0.        ]
 [ 0.        ]
 [ 4.37242979]
 [ 0.        ]
 [ 1.35027092]
 [ 2.20226098]
 [ 3.09230894]
 [ 0.36647609]
 [ 4.49610438]
 [13.22424592]
 [ 1.07189993]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [11.68938902]
 [ 6.35121311]
 [ 0.        ]
 [14.98114968]
 [ 6.2365328 ]
 [ 0.41251057]
 [ 0.38360753]
 [10.98727261]
 [16.55756738]
 [ 3.48667576]
 [ 1.20401548]
 [ 5.357552  ]
 [ 5.49749741]
 [15.54529076]
 [ 1.98506318]
 [ 0.        ]
 [ 8.83387109]
 [ 0.51025305]
 [14.40175978]
 [ 0.44466707]
 [ 3.20434421]
 [ 8.88138381]
 [ 0.        ]
 [ 5.11676397]
 [13.10787881]
 [ 2.21266271]
 [ 2.43578859]
 [ 0.        ]
 [ 3.78104491]
 [ 9.73361787]
 [14.34938247]
 [ 0.64210081]
 [ 7.62171344]
 [ 5.76271821]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.86591881]
 [13.16769218]
 [ 1.34930866]
 [ 2.44646799]
 [ 0.        ]
 [ 0.        ]
 [ 3.41925572]
 [ 0.        ]
 [ 8.15877427]
 [ 0.68670221]
 [ 1.61602828]
 [ 4.56503047]
 [10.97634788]
 [ 0.        ]
 [ 0.        ]
 [ 3.33104591]
 [ 1.08379203]
 [ 5.24548425]
 [10.6663957 ]
 [ 0.        ]
 [ 5.43159622]
 [10.21448245]
 [ 3.91093409]
 [ 0.        ]
 [ 8.46849738]
 [ 2.87068035]
 [ 9.86406029]
 [ 2.83080293]
 [ 3.55796143]
 [ 4.96936234]
 [ 6.01697316]
 [ 6.55435708]
 [13.98303533]
 [ 4.53083235]
 [ 0.        ]
 [ 3.52298476]
 [ 0.        ]
 [ 1.9689386 ]
 [ 5.67829167]
 [ 4.43584858]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.57531233]
 [ 0.        ]
 [ 4.76384708]
 [ 0.65580975]
 [ 0.43712118]
 [ 0.        ]
 [16.42490837]
 [ 0.        ]
 [ 4.88667207]
 [ 3.50712228]
 [ 4.55056826]
 [ 4.00036964]
 [ 5.53118181]
 [ 0.        ]
 [ 1.59817461]
 [ 5.66282928]
 [ 2.37409355]
 [13.27918231]
 [ 0.        ]
 [ 0.46602669]
 [ 2.92933653]
 [ 8.1732264 ]
 [ 0.        ]
 [ 1.91724078]
 [ 8.95447581]
 [ 1.80735492]
 [ 0.60179158]
 [ 3.93170197]
 [ 4.18914455]
 [10.7357887 ]
 [ 7.21097422]
 [ 2.61341378]
 [ 3.949703  ]
 [ 0.        ]
 [ 3.82463549]
 [ 7.26961202]
 [ 3.97077084]
 [ 8.80037513]
 [ 0.78232468]
 [ 0.        ]
 [ 5.2673635 ]
 [ 8.76785439]
 [ 0.        ]
 [13.463048  ]
 [ 9.43448333]
 [ 0.        ]
 [ 1.10936056]
 [ 0.        ]
 [ 8.19142792]
 [ 4.14061508]
 [ 1.60975496]
 [ 0.        ]
 [ 8.59402969]
 [ 2.02414235]
 [ 7.49727145]
 [ 1.23529817]
 [ 3.0579181 ]
 [ 0.65690818]
 [ 2.12944789]
 [13.98633498]
 [ 4.8024931 ]
 [ 3.46701857]
 [ 2.6112196 ]
 [ 1.59450078]
 [ 0.        ]
 [13.58370718]
 [11.54486323]
 [ 0.66193198]
 [ 0.        ]
 [10.70407162]
 [ 0.        ]
 [ 4.31802032]
 [ 2.18757774]
 [ 8.32223283]
 [12.87084902]
 [ 0.        ]
 [ 4.58038069]
 [ 0.        ]
 [ 0.51762845]
 [ 8.01954681]
 [14.08711699]
 [ 4.20611962]
 [ 0.56676645]
 [10.2221142 ]
 [ 4.41483912]
 [ 0.        ]
 [ 0.        ]
 [ 5.73863275]
 [ 0.34244096]
 [ 6.2048665 ]
 [ 0.        ]
 [10.81578434]
 [ 0.43306627]
 [ 7.85210811]
 [15.83553131]
 [ 5.04106772]
 [ 1.51131622]
 [ 0.        ]
 [ 9.90534759]
 [ 6.04935632]
 [ 1.50370491]
 [ 0.67716994]
 [ 2.83981853]
 [14.91603788]
 [ 0.        ]
 [ 0.        ]
 [11.47810691]
 [ 0.        ]
 [ 0.        ]
 [ 2.39689928]
 [ 2.21738584]
 [ 0.85575056]
 [ 3.3811726 ]
 [ 0.61466273]
 [ 2.13901101]
 [13.24574105]
 [ 6.25685404]
 [ 2.22949564]
 [ 0.        ]
 [ 0.33525457]
 [ 0.        ]
 [14.77184647]
 [ 8.95213638]
 [ 0.57046293]
 [15.77740111]
 [ 0.        ]
 [ 0.        ]
 [11.53276018]
 [14.07561814]
 [14.9936715 ]
 [ 0.56218136]
 [ 0.79360461]
 [ 0.94178242]
 [ 3.04514587]
 [ 0.97129523]
 [ 5.26634804]
 [16.23280415]
 [ 1.47809169]
 [ 7.25574809]
 [ 0.        ]
 [ 0.        ]
 [11.81194524]
 [ 0.43231807]
 [15.95241658]
 [ 0.        ]
 [ 0.38934654]
 [ 9.69624861]
 [13.93495279]
 [ 0.36311499]
 [ 2.08753073]
 [ 1.37150311]
 [17.43208682]
 [ 0.67978409]
 [13.11522388]
 [11.93021915]
 [ 0.32377356]
 [ 0.61711037]
 [12.43615762]
 [ 0.        ]
 [ 0.345737  ]
 [14.08113815]
 [ 3.03384584]
 [11.03884048]
 [ 4.80874542]
 [ 0.62442848]
 [ 0.        ]
 [ 9.14826201]
 [10.82859104]
 [ 3.67518363]
 [ 1.58009723]
 [ 8.17787096]
 [ 3.99600904]
 [ 7.31303266]
 [ 3.27061864]
 [ 0.38725224]
 [ 2.37926052]
 [15.58402891]
 [14.58307198]
 [15.49393771]
 [ 0.        ]
 [13.62487121]
 [ 7.88803147]
 [ 7.01987201]
 [ 7.65350219]
 [ 2.34559508]
 [ 0.        ]
 [ 3.75040284]
 [ 0.        ]
 [ 1.37189336]
 [10.61660242]
 [ 0.85551138]
 [11.23956201]
 [ 1.49400591]
 [12.13012337]
 [ 0.        ]
 [10.53819029]
 [ 3.94335876]
 [ 1.47814347]
 [ 0.        ]
 [ 1.37851162]
 [ 2.27884713]
 [ 7.05340137]
 [ 0.88362082]
 [ 0.        ]
 [ 2.98540935]
 [ 0.        ]
 [ 7.68385152]
 [ 1.18650056]
 [ 4.5844274 ]
 [ 0.        ]
 [11.82914225]
 [ 1.64284017]
 [ 1.10453795]
 [ 0.39363586]
 [ 2.64415624]
 [ 0.        ]
 [ 8.10007042]
 [11.50154887]
 [14.25001273]
 [ 0.        ]
 [ 0.        ]
 [ 0.58813294]
 [ 0.        ]
 [ 0.        ]
 [12.61912786]
 [14.19376696]
 [ 3.05814329]
 [17.03890118]
 [ 1.15639662]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 5.19766492]
 [ 5.02465655]
 [ 3.31956013]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [12.23117164]
 [ 0.92181714]
 [10.06322384]
 [ 0.        ]
 [ 0.        ]
 [ 2.07720881]
 [ 0.80859099]
 [13.67374635]
 [ 0.40925515]
 [ 1.06667476]
 [ 1.14639455]
 [ 6.46106684]
 [ 2.24731993]
 [ 2.24190118]
 [ 0.        ]
 [ 0.        ]
 [ 0.94425876]
 [ 3.22884947]
 [ 8.98122162]
 [ 0.39363586]
 [ 0.        ]
 [ 9.57701654]
 [ 7.95363017]
 [ 0.82651798]
 [ 0.        ]
 [ 0.39066769]
 [ 8.36771964]
 [ 0.        ]
 [ 0.40784218]
 [15.98552475]
 [ 0.36490856]
 [ 5.98822568]
 [ 0.        ]
 [ 0.        ]
 [ 9.52356078]
 [11.19071096]
 [ 0.        ]
 [ 1.17632277]
 [12.7309226 ]
 [ 2.87852918]
 [ 2.36370375]
 [10.32551459]
 [14.50134091]
 [ 4.66575658]
 [ 8.02580178]
 [ 2.87868611]
 [ 0.83955654]
 [ 0.        ]
 [15.01374227]
 [ 7.30924714]
 [ 0.        ]
 [ 2.58897242]
 [16.02903745]
 [ 5.87543851]
 [ 0.        ]
 [ 0.        ]
 [13.31157865]
 [ 3.18619944]
 [15.58296663]
 [ 0.        ]
 [ 5.85021685]
 [ 0.        ]
 [ 0.        ]
 [10.43698215]
 [ 0.60131618]
 [ 0.        ]
 [12.25017144]
 [ 0.        ]
 [ 0.62956645]
 [ 1.30789478]
 [ 2.00432161]
 [12.82946614]
 [ 3.27835653]
 [ 0.96561808]
 [ 0.        ]
 [ 3.61189237]
 [ 0.        ]
 [ 0.98863016]
 [ 3.3236727 ]
 [ 6.40899711]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 2.52511672]
 [ 6.29230323]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [12.56778984]
 [ 4.02985922]
 [ 2.05272888]
 [ 0.        ]
 [ 4.788101  ]
 [ 4.58056762]
 [14.50135347]
 [ 2.27953073]
 [ 0.        ]
 [ 0.        ]
 [14.92005141]
 [ 0.56345103]
 [ 4.0631146 ]
 [ 3.01076194]
 [12.75768294]
 [11.28410332]
 [ 1.00324242]
 [ 5.75509053]
 [ 7.60117799]
 [11.34768509]
 [ 0.        ]
 [ 0.50314517]
 [ 0.        ]
 [ 2.24190118]
 [ 3.26071822]
 [11.76677668]
 [ 1.68737428]]